### ISSUE TITLE
About PCN in VCNet

### ISSUE THREAD

**Issue by yc-cui** [xyfJASON/Image-Inpainting-Implementations#1]
I noticed another VCNet repo [https://github.com/birdortyedi/vcnet-blind-image-inpainting/blob/main/modules/normalization.py](https://github.com/birdortyedi/vcnet-blind-image-inpainting/blob/main/modules/normalization.py), when computing mean and std, he took `m` as an extra input for both `X_p` and `X_q`: 
```
    def _compute_T(self, x, m):
        X_p = x * m
        X_q = x * (1. - m)
        X_p_mean = self._compute_weighted_mean(X_p, m).unsqueeze(-1).unsqueeze(-1)
        X_p_std = self._compute_weighted_std(X_p, m).unsqueeze(-1).unsqueeze(-1)
        X_q_mean = self._compute_weighted_mean(X_q, m).unsqueeze(-1).unsqueeze(-1)
        X_q_std = self._compute_weighted_std(X_q, m).unsqueeze(-1).unsqueeze(-1)
        return ((X_p - X_p_mean) / X_p_std) * X_q_std + X_q_mean
```

In your repo, when computing mean and std, the mask is different:
```
    def _compute_T(self, X: Tensor, mask: Tensor):
        """ Note that `H` in the paper is actually 1 - mask here """
        X_p = X * (1. - mask)
        X_q = X * mask
        X_p_mean = self._compute_weighted_mean(X_p, 1. - mask)
        X_p_std = self._compute_weighted_std(X_p, 1. - mask)
        X_q_mean = self._compute_weighted_mean(X_q, mask)
        X_q_std = self._compute_weighted_std(X_q, mask)
        return ((X_p - X_p_mean) / X_p_std) * X_q_std + X_q_mean
```

Does that mean another repo is incorrect?

**Comment by xyfJASON** [comment]
Thanks for your comment! Yes, I think so. The mean and variance of `X_p` and `X_q` should be calculated in their corresponding area, so I think another repo made a mistake here.

Besides, you can also refer to the [official tensorflow repo](https://github.com/shepnerd/blindinpainting_vcnet/blob/master/tensorflow_version/net/layers.py#L27-L39) where known/unknown statistics are calculated on `mask_s` and `1-mask_s` respectively.

**Comment by yc-cui** [comment]
Thanks for your reply. :)
